/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.cajaFuerte;

import java.util.Scanner;

public class MenuCajaFuerte {
 
     public static void main(String[] args) {

        CajaFuerte miCaja = new CajaFuerte();
        String passInput;
        String passInput2;
        
        int menu;
        boolean exit;
        Scanner teclado = new Scanner(System.in);

        do {
            System.out.println("Seleccione una opción (0 - 2):");
            System.out.println("\n\t1. Asignar nueva combinación");
            System.out.println("\t2. Abrir caja fuerte");
            System.out.println("\n\t0. Salir\n\t");
            menu = teclado.nextInt();
            teclado.nextLine();
                        
            switch (menu) {
                case 1:

                    System.out.println("Introduzca la contraseña anterior (4 caracteres): ");
                    passInput = teclado.nextLine();
                    System.out.println("Introduzca una nueva contraseña (4 caracteres): ");
                    passInput2 = teclado.nextLine();
                    if (miCaja.changePassword(passInput, passInput2)) {
                        System.out.println("Contraseña cambiada correctamente");
                    } else {
                        System.out.println("ERROR: Contraseña incorrecta o invalida");
                    }

                    exit = false;
                    break;
                case 2:
                    System.out.println("Introduce la contraseña (4 caracteres): ");
                    passInput = teclado.nextLine();
                    teclado.reset();
                    if (miCaja.openBox(passInput)) {

                        System.out.println("¡Caja fuerte abierta!");

                    } else {

                        System.out.println("ERROR: Contraseña incorrecta...");

                    }
                    exit = false;
                    break;
                case 0:

                    exit = true;
                    break;
                default:
                    System.out.println("Por favor, introduzca una opción válida...");
                    exit = false;
            }
        } while (!exit);
    }
    
}
